# Generated by Django 2.0.7 on 2018-11-28 12:59

from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user_name', models.CharField(default='', max_length=10, verbose_name='用户名')),
                ('user_nickname', models.CharField(max_length=10, verbose_name='登录名')),
                ('user_phone', models.CharField(max_length=12, verbose_name='电话')),
                ('user_pwd', models.CharField(max_length=15, verbose_name='密码')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
        ),
    ]
