# Generated by Django 2.0.7 on 2018-12-01 09:54

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('infoSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('pla_id', models.AutoField(primary_key=True, serialize=False, verbose_name='平台id')),
                ('pla_name', models.CharField(max_length=20, verbose_name='平台名称')),
                ('pla_type', models.CharField(max_length=1, verbose_name='平台类型')),
                ('pla_adds', models.CharField(max_length=20, verbose_name='平台地址')),
                ('manage_adds', models.CharField(max_length=20, verbose_name='管理平台地址')),
                ('forward_adds', models.CharField(max_length=20, verbose_name='前置机地址')),
                ('appeui', models.CharField(max_length=20, verbose_name='AppEui')),
                ('pla_path', models.CharField(max_length=200, verbose_name='主站安装路径')),
                ('forward_path', models.CharField(max_length=200, verbose_name='前置机安装路径')),
                ('pla_time', models.DateTimeField(verbose_name='更新时间')),
                ('remake', models.CharField(max_length=500, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False, verbose_name='项目id')),
                ('pro_name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('pro_adds', models.CharField(max_length=20, verbose_name='项目地址')),
                ('pro_time', models.DateTimeField(verbose_name='创建时间')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='infoSys.User',
                                           verbose_name='创建人id')),
            ],
        ),
        migrations.CreateModel(
            name='SerInfo',
            fields=[
                ('ser_id', models.AutoField(primary_key=True, serialize=False, verbose_name='服务器id')),
                ('ser_name', models.CharField(max_length=20, verbose_name='服务器名称')),
                ('ser_adds', models.CharField(max_length=20, verbose_name='服务器地址')),
                ('ser_loginName', models.CharField(max_length=50, verbose_name='服务器登陆名')),
                ('ser_loginPwd', models.CharField(max_length=50, verbose_name='服务器密码')),
                ('ser_time', models.DateTimeField(verbose_name='更新时间')),
                ('projectInfo',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='infoSys.ProjectInfo',
                                   verbose_name='服务器所属项目id')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('ver_id', models.AutoField(primary_key=True, serialize=False, verbose_name='版本id')),
                ('ver_no', models.CharField(max_length=10, verbose_name='版本号')),
                ('ver_upd', models.CharField(max_length=500, verbose_name='修改内容')),
                ('ver_time', models.DateTimeField(verbose_name='更新时间')),
                ('ver_user', models.CharField(max_length=10, verbose_name='版本创建人')),
                ('platform',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='infoSys.Platform',
                                   verbose_name='版本号所属平台id')),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='serInfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='infoSys.SerInfo',
                                    verbose_name='平台所属服务器id'),
        ),
    ]
