# Generated by Django 2.0.7 on 2018-12-01 10:47

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('infoSys', '0002_auto_20181201_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='pla_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='serinfo',
            name='ser_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='version',
            name='ver_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
