# Generated by Django 2.0.7 on 2018-12-01 16:37

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('infoSys', '0003_auto_20181201_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='pro_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
